---
title: "CowPlots_GetLengends"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
path= dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(path)
getwd()

library(readr)
library(readxl)
library("writexl")
library(tidyverse)


library(ggplot2)  # FYI you need v2.0
library(dplyr)    # yes, i could have not done this and just used 'subset' instead of 'filter'
library(ggalt)    # devtools::install_github("hrbrmstr/ggalt")
library(ggthemes) # theme_map and tableau colors
library(viridis)

library(ggmap)
library(maps)
library(mapdata)

library(cowplot)   # get_legend() & plot_grid() functions
library(patchwork) # blank plot: plot_spacer()



```

```{r}

df <- read.csv("Data/brainhack-timeline_cleaned_YF.csv")
df_continent <- read.csv("Data/Brainhack timeline - Cleaned_plusContinent.csv")
#df_year2 <- read_csv("Brainhack timeline - Cleaned_BHG Events By Year_withEmptySpacePlaceholderForSunburst.csv")
```


#try get lendgent 

```{r}
#** Create each plot individually (color, and size)
# 1. Original plot without legend

df_event %>% group_by(country,region,year,freq) %>% 
p0 <- world+
  geom_point(
    data = df_event,
    aes(long, lat,fill= as.character(year), size= freq),
    colour = "white",shape=21, group=FALSE)) 
  #scale_fill_viridis_d(option="C",direction = -1,begin = 0.9,end = 0,alpha = 0.75) +
  theme_bw() + 
  theme_void() +# coordination info 
  theme(legend.position = "none")
  
  
# 2. Size  only
  
p1 <- world+
  geom_point(
    data = df_event,
    aes(long, lat,size= freq), shape=21) +
  theme(legend.key=element_rect(fill="transparent",
                                colour="transparent"))

# 3. Color only

p2 <- world+
  geom_point(
    data = df_event,
    aes(long, lat,colour= as.character(year))) + 
  #scale_fill_viridis_d(option="C",direction = -1,begin = 0.9,end = 0,alpha = 0.75) +
  guides(colour = guide_legend(override.aes = list(size=10)))+
  theme(legend.text=element_text(size=9))+
  theme(legend.key=element_rect(fill="transparent",
                                colour="transparent"))
  

#**Get all legends**

leg1 <-get_legend(p1)
leg2 <-get_legend(p2)


#**Create a blank plot for legend alignment**
blank_p <- plot_spacer() + theme_void()

#**Combine legends**
leg12 <- plot_grid(leg1, leg2,
                   blank_p,
                   nrow = 2)


# **Put everything together** But the figure somehow strench and too small 

# final_p <- plot_grid(p0,
#                      leg12,
#                      nrow = 1,
#                      align = "hv",
#                      rel_widths = c(1, 0.3))

#print(final_p)

print(p0)
print(leg12)

# save the fig
#library(svglite)
ggsave("Output//buublemap_1.png",p0,dpi = 300, width = 5, height = 3)
ggsave2("Output//buublemap_1_led.png",leg12,dpi = 300)





```
