---
title: "Interactive_bublleMaps"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}
rm(list=ls())
path= dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(path)
getwd()

library(readr)
library(readxl)
library("writexl")
library(tidyverse)


library(ggplot2)  # FYI you need v2.0
library(dplyr)    # yes, i could have not done this and just used 'subset' instead of 'filter'
library(ggalt)    # devtools::install_github("hrbrmstr/ggalt")
library(ggthemes) # theme_map and tableau colors
library(viridis)

library(ggmap)
library(maps)
library(mapdata)

library(cowplot)   # get_legend() & plot_grid() functions
library(patchwork) # blank plot: plot_spacer()



```


```{r interactive map }

#https://www.r-graph-gallery.com/330-bubble-map-with-ggplot2.html

wr <- map_data("world")%>% filter(region!="Antarctica")
# Load the plotly package
library(plotly)

 
# Rorder data + Add a new column with tooltip text
data <- df_event_des%>%
  arrange(freq) %>%
  mutate( name=factor(region, unique(region))) %>%
  mutate( mytext=paste(
    "City: ", region, "\n", 
    " ", event, sep="")
  )
 
# Make the map (static)
p <- ggplot() +
  geom_polygon(data =wr,aes(long, lat,  group = group), size = 0.1, alpha=0.9)+
  geom_point(data = data,aes(long, lat,fill= factor(year), size= freq, text=mytext),
             colour = "white",shape=21,alpha = 0.7) +
  scale_size(range = c(3, 12), name="Frequency")+
  scale_color_viridis(option="inferno")+
  theme_void() +
  #coord_map() +
  theme(legend.position = "none")
 
p <- ggplotly(p, tooltip="text")

p


# save it!
library(leaflet)
htmlwidgets::saveWidget(p, "Brainhack_bubbleMap.html", selfcontained = T)

# save the widget in a html file if needed.
library(htmlwidgets)
saveWidget(p, "bubblemapBrainhack.html")
saveWidget(p, file=paste0( getwd(), "bubblemapBrainhack.html"))
```




